---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Update
      apt:
        update_cache: true
        force_apt_get: true
    - name: Install JDK
      ansible.builtin.apt: 
        pkg: openjdk-8-jdk
        state: present
    - name: Add Group tomcat 
      group: 
        name: tomcat
        state: present
    - name: Add User tomcat
      user: 
        name: tomcat
        group: tomcat
        shell: /bin/false
        home: /opt/tomcat
    - name: Download tomcat package
      get_url: 
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.tar.gz
        dest: /home/devops/Downloads/
    - name: Unzip tomcat package
      unarchive: 
        src: /home/devops/Downloads/apache-tomcat-8.5.37.tar.gz 
        dest: /opt/tomcat
        extra_opts: 
          - --strip-components=1
    - name: Change Group Access
      file:
        recurse: yes
        group: tomcat
        path: /opt/tomcat
        state: directory
    - name: Give Read permission to group on conf folder
      file: 
        path: /opt/tomcat/conf 
        recurse: yes 
        mode: g+r
    - name: Give Exec permission to group on conf folder
      file: 
        path: /opt/tomcat/conf 
        mode: g+x
    - name: Change Owner Access
      file: 
        path: "{{ item }}"
        owner: tomcat
        state: directory
      loop: 
        - /opt/tomcat/webapps
        - /opt/tomcat/work
        - /opt/tomcat/temp 
        - /opt/tomcat/logs
    - name: Replace tomcat.service file 
      copy:
        src: /home/devops/tomcat-maven/tomcat.service
        dest: /etc/systemd/system/tomcat.service
    - name: Reload systemctl
      command: systemctl daemon-reload
    - name: Start Tomcat
      service:
        name: tomcat
        state: started